import { Movie, FriendActivity } from './types';

export const allMovies: Movie[] = [
  { id: 1, title: 'Interstellar', releaseYear: 2014, runtime: 169, genres: ['Sci-Fi', 'Adventure', 'Drama'], director: 'Christopher Nolan', cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'], country: 'USA', language: 'English', overview: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.', backdropUrl: 'https://image.tmdb.org/t/p/original/xJHokMbljvjEVAeUCNXnMof2wz0.jpg', posterUrl: 'https://image.tmdb.org/t/p/w500/gEU2QlsUUHXjNpeMacz875JVcbz.jpg', rating: 4.8 },
  { id: 2, title: 'Dune', releaseYear: 2021, runtime: 155, genres: ['Sci-Fi', 'Adventure'], director: 'Denis Villeneuve', cast: ['Timothée Chalamet', 'Zendaya', 'Oscar Isaac'], country: 'USA', language: 'English', overview: 'Paul Atreides unites with the Fremen while on a warpath of revenge against those who destroyed his family.', backdropUrl: 'https://image.tmdb.org/t/p/original/lzWHmYdfeFiMIY4JaMmtR7GEli3.jpg', posterUrl: 'https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg', rating: 4.6 },
  { id: 3, title: 'The Batman', releaseYear: 2022, runtime: 176, genres: ['Crime', 'Mystery', 'Thriller'], director: 'Matt Reeves', cast: ['Robert Pattinson', 'Zoë Kravitz', 'Paul Dano'], country: 'USA', language: 'English', overview: 'Batman ventures into Gotham City\'s underworld when a sadistic killer leaves behind a trail of cryptic clues.', backdropUrl: 'https://image.tmdb.org/t/p/original/5P8SmMzSNYikXpzilOPLcLxQhB2.jpg', posterUrl: 'https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg', rating: 4.5 },
  { id: 4, title: 'Oppenheimer', releaseYear: 2023, runtime: 180, genres: ['Drama', 'History'], director: 'Christopher Nolan', cast: ['Cillian Murphy', 'Emily Blunt', 'Robert Downey Jr.'], country: 'USA', language: 'English', overview: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.', backdropUrl: 'https://image.tmdb.org/t/p/original/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg', posterUrl: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg', rating: 4.9 },
  { id: 5, title: 'Inception', releaseYear: 2010, runtime: 148, genres: ['Sci-Fi', 'Action', 'Thriller'], director: 'Christopher Nolan', cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page'], country: 'USA', language: 'English', overview: 'A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.', backdropUrl: 'https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg', posterUrl: 'https://image.tmdb.org/t/p/w500/ljsZTbVsrQSqZgWeep2B1QiDKuh.jpg', rating: 4.7 },
  { id: 6, title: 'The Dark Knight', releaseYear: 2008, runtime: 152, genres: ['Action', 'Crime', 'Drama'], director: 'Christopher Nolan', cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'], country: 'USA', language: 'English', overview: 'When the menace known as the Joker wreaks havoc on Gotham, Batman must confront one of the greatest psychological tests.', backdropUrl: 'https://image.tmdb.org/t/p/original/nMKdUUepR0i5zn0y1T4CsSB5ez.jpg', posterUrl: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911BTUgMe1nqVQ.jpg', rating: 4.9 },
  { id: 7, title: 'Blade Runner 2049', releaseYear: 2017, runtime: 164, genres: ['Sci-Fi', 'Drama', 'Mystery'], director: 'Denis Villeneuve', cast: ['Ryan Gosling', 'Harrison Ford', 'Ana de Armas'], country: 'USA', language: 'English', overview: 'Young Blade Runner K\'s discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard.', backdropUrl: 'https://image.tmdb.org/t/p/original/ilRyazdMJwN05exqhwK4tMKBYZs.jpg', posterUrl: 'https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg', rating: 4.5 },
  { id: 8, title: 'Parasite', releaseYear: 2019, runtime: 132, genres: ['Drama', 'Thriller', 'Comedy'], director: 'Bong Joon-ho', cast: ['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong'], country: 'South Korea', language: 'Korean', overview: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.', backdropUrl: 'https://image.tmdb.org/t/p/original/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg', posterUrl: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg', rating: 4.8 },
  { id: 9, title: 'Whiplash', releaseYear: 2014, runtime: 107, genres: ['Drama', 'Music'], director: 'Damien Chazelle', cast: ['Miles Teller', 'J.K. Simmons'], country: 'USA', language: 'English', overview: 'A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing.', backdropUrl: 'https://image.tmdb.org/t/p/original/6bbZ6XyvgfjhQwbplnUh1LSj1ky.jpg', posterUrl: 'https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedos.jpg', rating: 4.7 },
  { id: 10, title: 'Everything Everywhere All at Once', releaseYear: 2022, runtime: 139, genres: ['Action', 'Adventure', 'Comedy'], director: 'Daniel Kwan', cast: ['Michelle Yeoh', 'Ke Huy Quan', 'Stephanie Hsu'], country: 'USA', language: 'English', overview: 'An aging Chinese immigrant is swept up in an insane adventure where she alone can save the multiverse.', backdropUrl: 'https://image.tmdb.org/t/p/original/fhquRW28vRZHr26orSaFFnhYIA0.jpg', posterUrl: 'https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg', rating: 4.6 },
  { id: 11, title: 'Arrival', releaseYear: 2016, runtime: 116, genres: ['Sci-Fi', 'Drama'], director: 'Denis Villeneuve', cast: ['Amy Adams', 'Jeremy Renner', 'Forest Whitaker'], country: 'USA', language: 'English', overview: 'A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.', backdropUrl: 'https://image.tmdb.org/t/p/original/yIZ1xendyqKvY3FGeeUYUd5X9Mm.jpg', posterUrl: 'https://image.tmdb.org/t/p/w500/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg', rating: 4.5 },
  { id: 12, title: 'Mad Max: Fury Road', releaseYear: 2015, runtime: 120, genres: ['Action', 'Adventure', 'Sci-Fi'], director: 'George Miller', cast: ['Tom Hardy', 'Charlize Theron', 'Nicholas Hoult'], country: 'Australia', language: 'English', overview: 'In a post-apocalyptic wasteland, Max teams up with Furiosa to flee from a cult leader and his army.', backdropUrl: 'https://image.tmdb.org/t/p/original/phszHPFVhPHhMZgo0fWTKBDQsJA.jpg', posterUrl: 'https://image.tmdb.org/t/p/w500/hA2ple9q4qnwxp3hKVNhroipsir.jpg', rating: 4.6 },
  { id: 13, title: 'Spirited Away', releaseYear: 2001, runtime: 125, genres: ['Animation', 'Adventure', 'Fantasy'], director: 'Hayao Miyazaki', cast: ['Rumi Hiiragi', 'Miyu Irino'], country: 'Japan', language: 'Japanese', overview: 'During her family\'s move, Chihiro wanders into a world ruled by gods, witches, and spirits, where humans are changed into beasts.', backdropUrl: 'https://image.tmdb.org/t/p/original/6oaL4DP75yABrd5EbC4H2cuwBBz.jpg', posterUrl: 'https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg', rating: 4.8 },
  { id: 14, title: 'The Social Network', releaseYear: 2010, runtime: 120, genres: ['Drama', 'History'], director: 'David Fincher', cast: ['Jesse Eisenberg', 'Andrew Garfield', 'Justin Timberlake'], country: 'USA', language: 'English', overview: 'The founding of Facebook and the resulting lawsuits.', backdropUrl: 'https://image.tmdb.org/t/p/original/cMXFsJPDGuo3lqpPdNiXHmK3D3f.jpg', posterUrl: 'https://image.tmdb.org/t/p/w500/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg', rating: 4.4 },
  { id: 15, title: 'No Country for Old Men', releaseYear: 2007, runtime: 122, genres: ['Crime', 'Drama', 'Thriller'], director: 'Joel Coen', cast: ['Javier Bardem', 'Josh Brolin', 'Tommy Lee Jones'], country: 'USA', language: 'English', overview: 'Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash.', backdropUrl: 'https://image.tmdb.org/t/p/original/bj1v6YKF8yHqA489GFfAWcrZTFy.jpg', posterUrl: 'https://image.tmdb.org/t/p/w500/bj1v6YKF8yHqA489GFfAWcrZTFy.jpg', rating: 4.6 },
  { id: 16, title: 'The Grand Budapest Hotel', releaseYear: 2014, runtime: 99, genres: ['Comedy', 'Adventure', 'Crime'], director: 'Wes Anderson', cast: ['Ralph Fiennes', 'Tony Revolori', 'F. Murray Abraham'], country: 'Germany', language: 'English', overview: 'The adventures of a legendary concierge at a famous European hotel between the wars.', backdropUrl: 'https://image.tmdb.org/t/p/original/nX5XotM9yprCKarRH4fzOq1VM1J.jpg', posterUrl: 'https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg', rating: 4.5 },
  { id: 17, title: 'Fight Club', releaseYear: 1999, runtime: 139, genres: ['Drama', 'Thriller'], director: 'David Fincher', cast: ['Brad Pitt', 'Edward Norton', 'Helena Bonham Carter'], country: 'USA', language: 'English', overview: 'An insomniac office worker and a devil-may-care soap maker form an underground fight club.', backdropUrl: 'https://image.tmdb.org/t/p/original/hZkgoQYus5dXo3H8T7Uef6DNknx.jpg', posterUrl: 'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg', rating: 4.8 },
  { id: 18, title: 'The Shawshank Redemption', releaseYear: 1994, runtime: 142, genres: ['Drama'], director: 'Frank Darabont', cast: ['Tim Robbins', 'Morgan Freeman'], country: 'USA', language: 'English', overview: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', backdropUrl: 'https://image.tmdb.org/t/p/original/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg', posterUrl: 'https://image.tmdb.org/t/p/w500/9cjIGRRQ1cv0MxDJIkEJEjOWVIC.jpg', rating: 4.9 },
  { id: 19, title: 'Pulp Fiction', releaseYear: 1994, runtime: 154, genres: ['Crime', 'Drama', 'Comedy'], director: 'Quentin Tarantino', cast: ['John Travolta', 'Uma Thurman', 'Samuel L. Jackson'], country: 'USA', language: 'English', overview: 'The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.', backdropUrl: 'https://image.tmdb.org/t/p/original/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg', posterUrl: 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg', rating: 4.7 },
  { id: 20, title: 'Your Name', releaseYear: 2016, runtime: 106, genres: ['Animation', 'Romance', 'Drama'], director: 'Makoto Shinkai', cast: ['Ryunosuke Kamiki', 'Mone Kamishiraishi'], country: 'Japan', language: 'Japanese', overview: 'Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?', backdropUrl: 'https://image.tmdb.org/t/p/original/dIWwZW7dJJtqC6CgWzYkNVKIUm2.jpg', posterUrl: 'https://image.tmdb.org/t/p/w500/q719jXXEzOoYaps6babgKnONONX.jpg', rating: 4.7 },
];

export const allGenres = [...new Set(allMovies.flatMap(m => m.genres))].sort();

export const mockFriendsList = [
  { name: 'Rahul', avatarUrl: 'https://i.pravatar.cc/150?u=rahul', matchPercent: 92 },
  { name: 'Arjun', avatarUrl: 'https://i.pravatar.cc/150?u=arjun', matchPercent: 87 },
  { name: 'Meera', avatarUrl: 'https://i.pravatar.cc/150?u=meera', matchPercent: 78 },
  { name: 'Vikram', avatarUrl: 'https://i.pravatar.cc/150?u=vikram', matchPercent: 65 },
  { name: 'Priya', avatarUrl: 'https://i.pravatar.cc/150?u=priya', matchPercent: 81 },
];

export const mockFriendsActivity: FriendActivity[] = [
  { id: 'f1', user: { name: 'Rahul', avatarUrl: 'https://i.pravatar.cc/150?u=rahul' }, action: 'watched', movieId: 2, rating: 5, timeAgo: '2h ago' },
  { id: 'f2', user: { name: 'Arjun', avatarUrl: 'https://i.pravatar.cc/150?u=arjun' }, action: 'rated', movieId: 1, rating: 5, timeAgo: '4h ago' },
  { id: 'f3', user: { name: 'Meera', avatarUrl: 'https://i.pravatar.cc/150?u=meera' }, action: 'completed', movieId: 6, rating: 5, timeAgo: '6h ago' },
  { id: 'f4', user: { name: 'Vikram', avatarUrl: 'https://i.pravatar.cc/150?u=vikram' }, action: 'reviewed', movieId: 8, rating: 4, timeAgo: '8h ago' },
  { id: 'f5', user: { name: 'Priya', avatarUrl: 'https://i.pravatar.cc/150?u=priya' }, action: 'watched', movieId: 5, rating: 5, timeAgo: '12h ago' },
];

export const moods = ['Inspired', 'Melancholic', 'Thrilled', 'Nostalgic', 'Mind-blown', 'Emotional', 'Peaceful', 'Disturbed', 'Amused', 'Reflective'];
